### ISSUE TITLE
avahi-resolve-address equivalent in zeroconf

### ISSUE THREAD

**Issue by realnitinworks** [python-zeroconf/python-zeroconf#1124] opened 2023-01-25 17:45 UTC
Given an IP address, avahi-resolve-address is able to return the hostname of the IP(published by the avahi-daemon). Is it possible to do the same with zeroconf ? Please let me know how this can be done.

**Comment by bdraco** [comment] 2023-12-17 17:03
duplicate of https://github.com/python-zeroconf/python-zeroconf/issues/129

**Closed by bdraco** 2023-12-17 17:03 UTC
